// utils/cityMap.js
// Comprehensive city-to-country lookup map.
// Keys are lowercase city names; values are ISO 3166-1 alpha-2 country codes.
// Includes: all world capitals, top cities by population for 80+ countries,
// common alternate spellings, and US state abbreviations.

export const CITY_TO_COUNTRY = new Map([
  // A
  ["abidjan", "CI"],
  ["abu dhabi", "AE"],
  ["abuja", "NG"],
  ["accra", "GH"],
  ["adana", "TR"],
  ["addis ababa", "ET"],
  ["adelaide", "AU"],
  ["aden", "YE"],
  ["ahmedabad", "IN"],
  ["ak", "US"],
  ["al", "US"],
  ["al ain", "AE"],
  ["aleppo", "SY"],
  ["alexandria", "EG"],
  ["algiers", "DZ"],
  ["almaty", "KZ"],
  ["amman", "JO"],
  ["amsterdam", "NL"],
  ["anchorage", "US"],
  ["andorra la vella", "AD"],
  ["ankara", "TR"],
  ["antananarivo", "MG"],
  ["antwerp", "BE"],
  ["apia", "WS"],
  ["ar", "US"],
  ["ashgabat", "TM"],
  ["asmara", "ER"],
  ["astana", "KZ"],
  ["asuncion", "PY"],
  ["athens", "GR"],
  ["atlanta", "US"],
  ["auckland", "NZ"],
  ["austin", "US"],
  ["az", "US"],

  // B
  ["baghdad", "IQ"],
  ["baku", "AZ"],
  ["baltimore", "US"],
  ["bamako", "ML"],
  ["bandar seri begawan", "BN"],
  ["bandung", "ID"],
  ["bangalore", "IN"],
  ["bengaluru", "IN"],
  ["bangkok", "TH"],
  ["bangui", "CF"],
  ["banjul", "GM"],
  ["barcelona", "ES"],
  ["barranquilla", "CO"],
  ["basra", "IQ"],
  ["basse-terre", "GP"],
  ["basseterre", "KN"],
  ["beijing", "CN"],
  ["beirut", "LB"],
  ["belem", "BR"],
  ["belfast", "GB"],
  ["belgrade", "RS"],
  ["belize city", "BZ"],
  ["belmopan", "BZ"],
  ["belo horizonte", "BR"],
  ["berlin", "DE"],
  ["bern", "CH"],
  ["bilbao", "ES"],
  ["birmingham", "GB"],
  ["bishkek", "KG"],
  ["bissau", "GW"],
  ["bogota", "CO"],
  ["bombay", "IN"],
  ["boston", "US"],
  ["brasilia", "BR"],
  ["bratislava", "SK"],
  ["brazzaville", "CG"],
  ["bridgetown", "BB"],
  ["brisbane", "AU"],
  ["brussels", "BE"],
  ["bucharest", "RO"],
  ["budapest", "HU"],
  ["buenos aires", "AR"],
  ["bujumbura", "BI"],
  ["busan", "KR"],
  ["busan", "KR"],

  // C
  ["ca", "US"],
  ["cairo", "EG"],
  ["calcutta", "IN"],
  ["cali", "CO"],
  ["calgary", "CA"],
  ["canberra", "AU"],
  ["cape town", "ZA"],
  ["caracas", "VE"],
  ["cardiff", "GB"],
  ["cartagena", "CO"],
  ["casablanca", "MA"],
  ["castries", "LC"],
  ["cebu", "PH"],
  ["changsha", "CN"],
  ["charlotte", "US"],
  ["chengdu", "CN"],
  ["chennai", "IN"],
  ["chicago", "US"],
  ["chisinau", "MD"],
  ["chittagong", "BD"],
  ["chongqing", "CN"],
  ["christchurch", "NZ"],
  ["co", "US"],
  ["cologne", "DE"],
  ["colombo", "LK"],
  ["conakry", "GN"],
  ["copenhagen", "DK"],
  ["cordoba", "AR"],
  ["ct", "US"],
  ["curitiba", "BR"],

  // D
  ["daegu", "KR"],
  ["daejeon", "KR"],
  ["dakar", "SN"],
  ["dallas", "US"],
  ["damascus", "SY"],
  ["dar es salaam", "TZ"],
  ["dc", "US"],
  ["de", "US"],
  ["delhi", "IN"],
  ["denver", "US"],
  ["detroit", "US"],
  ["dhaka", "BD"],
  ["dili", "TL"],
  ["djibouti", "DJ"],
  ["dodoma", "TZ"],
  ["doha", "QA"],
  ["douala", "CM"],
  ["dresden", "DE"],
  ["dubai", "AE"],
  ["dublin", "IE"],
  ["durban", "ZA"],
  ["dushanbe", "TJ"],
  ["dusseldorf", "DE"],

  // E
  ["edinburgh", "GB"],
  ["edmonton", "CA"],
  ["el paso", "US"],

  // F
  ["faisalabad", "PK"],
  ["fl", "US"],
  ["florence", "IT"],
  ["fortaleza", "BR"],
  ["frankfurt", "DE"],
  ["freetown", "SL"],
  ["fukuoka", "JP"],
  ["funafuti", "TV"],

  // G
  ["ga", "US"],
  ["gaborone", "BW"],
  ["gaza", "PS"],
  ["gdansk", "PL"],
  ["geneva", "CH"],
  ["genoa", "IT"],
  ["georgetown", "GY"],
  ["gitega", "BI"],
  ["glasgow", "GB"],
  ["guadalajara", "MX"],
  ["guangzhou", "CN"],
  ["guatemala city", "GT"],
  ["guayaquil", "EC"],

  // H
  ["ha noi", "VN"],
  ["hamburg", "DE"],
  ["hamilton", "BM"],
  ["hanoi", "VN"],
  ["harare", "ZW"],
  ["havana", "CU"],
  ["helsinki", "FI"],
  ["hi", "US"],
  ["ho chi minh city", "VN"],
  ["hobart", "AU"],
  ["hong kong", "HK"],
  ["honiara", "SB"],
  ["houston", "US"],
  ["hyderabad", "IN"],

  // I
  ["ia", "US"],
  ["id", "US"],
  ["il", "US"],
  ["in", "US"],
  ["incheon", "KR"],
  ["indianapolis", "US"],
  ["islamabad", "PK"],
  ["istanbul", "TR"],
  ["izmir", "TR"],

  // J
  ["jaipur", "IN"],
  ["jakarta", "ID"],
  ["jeddah", "SA"],
  ["jerusalem", "IL"],
  ["johannesburg", "ZA"],

  // K
  ["kabul", "AF"],
  ["kampala", "UG"],
  ["kanpur", "IN"],
  ["karachi", "PK"],
  ["kathmandu", "NP"],
  ["khartoum", "SD"],
  ["khulna", "BD"],
  ["kigali", "RW"],
  ["kingston", "JM"],
  ["kingstown", "VC"],
  ["kinshasa", "CD"],
  ["kolkata", "IN"],
  ["krakow", "PL"],
  ["ks", "US"],
  ["kuala lumpur", "MY"],
  ["kumasi", "GH"],
  ["kunming", "CN"],
  ["kuwait city", "KW"],
  ["ky", "US"],
  ["kyiv", "UA"],
  ["kyoto", "JP"],

  // L
  ["la", "US"],
  ["la paz", "BO"],
  ["lagos", "NG"],
  ["lahore", "PK"],
  ["las vegas", "US"],
  ["libreville", "GA"],
  ["lilongwe", "MW"],
  ["lima", "PE"],
  ["lisbon", "PT"],
  ["ljubljana", "SI"],
  ["lome", "TG"],
  ["london", "GB"],
  ["los angeles", "US"],
  ["luanda", "AO"],
  ["lucknow", "IN"],
  ["lusaka", "ZM"],
  ["luxembourg", "LU"],
  ["lyon", "FR"],

  // M
  ["ma", "US"],
  ["macau", "MO"],
  ["madras", "IN"],
  ["madrid", "ES"],
  ["majuro", "MH"],
  ["malabo", "GQ"],
  ["male", "MV"],
  ["managua", "NI"],
  ["manama", "BH"],
  ["manaus", "BR"],
  ["manchester", "GB"],
  ["manila", "PH"],
  ["maputo", "MZ"],
  ["maracaibo", "VE"],
  ["marrakech", "MA"],
  ["marseille", "FR"],
  ["maseru", "LS"],
  ["mbabane", "SZ"],
  ["md", "US"],
  ["me", "US"],
  ["mecca", "SA"],
  ["medan", "ID"],
  ["medellin", "CO"],
  ["melbourne", "AU"],
  ["memphis", "US"],
  ["mexico city", "MX"],
  ["mi", "US"],
  ["miami", "US"],
  ["milan", "IT"],
  ["milwaukee", "US"],
  ["minneapolis", "US"],
  ["minsk", "BY"],
  ["mn", "US"],
  ["mo", "US"],
  ["mogadishu", "SO"],
  ["monaco", "MC"],
  ["monrovia", "LR"],
  ["monterrey", "MX"],
  ["montevideo", "UY"],
  ["montreal", "CA"],
  ["moroni", "KM"],
  ["moscow", "RU"],
  ["ms", "US"],
  ["mt", "US"],
  ["mumbai", "IN"],
  ["munich", "DE"],
  ["muscat", "OM"],

  // N
  ["n'djamena", "TD"],
  ["nagoya", "JP"],
  ["nairobi", "KE"],
  ["nanjing", "CN"],
  ["naples", "IT"],
  ["nassau", "BS"],
  ["naypyidaw", "MM"],
  ["nc", "US"],
  ["nd", "US"],
  ["ne", "US"],
  ["new delhi", "IN"],
  ["new orleans", "US"],
  ["new york", "US"],
  ["new york city", "US"],
  ["newcastle", "GB"],
  ["nh", "US"],
  ["niamey", "NE"],
  ["nice", "FR"],
  ["nicosia", "CY"],
  ["nj", "US"],
  ["nm", "US"],
  ["nouakchott", "MR"],
  ["noumea", "NC"],
  ["novosibirsk", "RU"],
  ["nuku'alofa", "TO"],
  ["nuremberg", "DE"],
  ["nv", "US"],
  ["ny", "US"],
  ["nyc", "US"],

  // O
  ["oh", "US"],
  ["ok", "US"],
  ["or", "US"],
  ["oran", "DZ"],
  ["osaka", "JP"],
  ["oslo", "NO"],
  ["ottawa", "CA"],
  ["ouagadougou", "BF"],

  // P
  ["pa", "US"],
  ["palikir", "FM"],
  ["panama city", "PA"],
  ["papeete", "PF"],
  ["paramaribo", "SR"],
  ["paris", "FR"],
  ["peking", "CN"],
  ["perth", "AU"],
  ["peshawar", "PK"],
  ["phnom penh", "KH"],
  ["philadelphia", "US"],
  ["phoenix", "US"],
  ["pittsburgh", "US"],
  ["podgorica", "ME"],
  ["port au prince", "HT"],
  ["port louis", "MU"],
  ["port moresby", "PG"],
  ["port of spain", "TT"],
  ["port-au-prince", "HT"],
  ["port-vila", "VU"],
  ["porto", "PT"],
  ["porto alegre", "BR"],
  ["porto-novo", "BJ"],
  ["prague", "CZ"],
  ["praia", "CV"],
  ["pretoria", "ZA"],
  ["pristina", "XK"],
  ["puebla", "MX"],
  ["pune", "IN"],
  ["pyongyang", "KP"],

  // Q
  ["quezon city", "PH"],
  ["quito", "EC"],

  // R
  ["rabat", "MA"],
  ["rajkot", "IN"],
  ["rangoon", "MM"],
  ["rawalpindi", "PK"],
  ["recife", "BR"],
  ["reykjavik", "IS"],
  ["ri", "US"],
  ["riga", "LV"],
  ["rio de janeiro", "BR"],
  ["riyadh", "SA"],
  ["rome", "IT"],
  ["rosario", "AR"],
  ["rotterdam", "NL"],

  // S
  ["saigon", "VN"],
  ["saint george's", "GD"],
  ["saint john's", "AG"],
  ["salt lake city", "US"],
  ["salvador", "BR"],
  ["san antonio", "US"],
  ["san diego", "US"],
  ["san francisco", "US"],
  ["san jose", "CR"],
  ["san jose", "US"],
  ["san juan", "PR"],
  ["san marino", "SM"],
  ["san salvador", "SV"],
  ["sana'a", "YE"],
  ["sanaa", "YE"],
  ["santiago", "CL"],
  ["santo domingo", "DO"],
  ["sao paulo", "BR"],
  ["sao tome", "ST"],
  ["sapporo", "JP"],
  ["sarajevo", "BA"],
  ["sc", "US"],
  ["sd", "US"],
  ["seattle", "US"],
  ["seoul", "KR"],
  ["seville", "ES"],
  ["sf", "US"],
  ["shanghai", "CN"],
  ["sharjah", "AE"],
  ["shenyang", "CN"],
  ["shenzhen", "CN"],
  ["singapore", "SG"],
  ["skopje", "MK"],
  ["sofia", "BG"],
  ["st louis", "US"],
  ["st. petersburg", "RU"],
  ["stockholm", "SE"],
  ["strasbourg", "FR"],
  ["stuttgart", "DE"],
  ["sucre", "BO"],
  ["surabaya", "ID"],
  ["surat", "IN"],
  ["suva", "FJ"],
  ["sydney", "AU"],

  // T
  ["taipei", "TW"],
  ["tallinn", "EE"],
  ["tashkent", "UZ"],
  ["tbilisi", "GE"],
  ["tegucigalpa", "HN"],
  ["tehran", "IR"],
  ["tel aviv", "IL"],
  ["the hague", "NL"],
  ["thimphu", "BT"],
  ["tianjin", "CN"],
  ["tijuana", "MX"],
  ["tirana", "AL"],
  ["tn", "US"],
  ["tokyo", "JP"],
  ["toronto", "CA"],
  ["toulouse", "FR"],
  ["tripoli", "LY"],
  ["tunis", "TN"],
  ["turin", "IT"],
  ["tx", "US"],

  // U
  ["ulaanbaatar", "MN"],
  ["ut", "US"],

  // V
  ["va", "US"],
  ["vaduz", "LI"],
  ["valencia", "ES"],
  ["valletta", "MT"],
  ["vancouver", "CA"],
  ["vatican city", "VA"],
  ["victoria", "SC"],
  ["vienna", "AT"],
  ["vientiane", "LA"],
  ["vilnius", "LT"],
  ["vt", "US"],

  // W
  ["wa", "US"],
  ["warsaw", "PL"],
  ["washington", "US"],
  ["washington d.c.", "US"],
  ["washington dc", "US"],
  ["wellington", "NZ"],
  ["wi", "US"],
  ["windhoek", "NA"],
  ["winnipeg", "CA"],
  ["wuhan", "CN"],
  ["wv", "US"],
  ["wy", "US"],

  // X
  ["xi'an", "CN"],
  ["xian", "CN"],

  // Y
  ["yamoussoukro", "CI"],
  ["yangon", "MM"],
  ["yaounde", "CM"],
  ["yerevan", "AM"],
  ["yokohama", "JP"],

  // Z
  ["zagreb", "HR"],
  ["zhengzhou", "CN"],
  ["zurich", "CH"],

  // ── Additional cities to reach 500+ entries ──

  // More African cities
  ["abeokuta", "NG"],
  ["agadir", "MA"],
  ["benin city", "NG"],
  ["blantyre", "MW"],
  ["bouake", "CI"],
  ["bulawayo", "ZW"],
  ["calabar", "NG"],
  ["dire dawa", "ET"],
  ["durban", "ZA"],
  ["east london", "ZA"],
  ["enugu", "NG"],
  ["fez", "MA"],
  ["goma", "CD"],
  ["ibadan", "NG"],
  ["kaduna", "NG"],
  ["kano", "NG"],
  ["kisumu", "KE"],
  ["lubumbashi", "CD"],
  ["lusaka", "ZM"],
  ["maiduguri", "NG"],
  ["mombasa", "KE"],
  ["nakuru", "KE"],
  ["ndola", "ZM"],
  ["ogbomosho", "NG"],
  ["omdurman", "SD"],
  ["oshogbo", "NG"],
  ["port elizabeth", "ZA"],
  ["port harcourt", "NG"],
  ["soweto", "ZA"],
  ["tangier", "MA"],
  ["tema", "GH"],
  ["tripoli", "LY"],
  ["zanzibar", "TZ"],

  // More Asian cities
  ["ahvaz", "IR"],
  ["amritsar", "IN"],
  ["antalya", "TR"],
  ["bacolod", "PH"],
  ["bhopal", "IN"],
  ["busan", "KR"],
  ["chandigarh", "IN"],
  ["changchun", "CN"],
  ["coimbatore", "IN"],
  ["da nang", "VN"],
  ["dalian", "CN"],
  ["davao", "PH"],
  ["dongguan", "CN"],
  ["esfahan", "IR"],
  ["foshan", "CN"],
  ["fuzhou", "CN"],
  ["guwahati", "IN"],
  ["gwangju", "KR"],
  ["haifa", "IL"],
  ["haikou", "CN"],
  ["hangzhou", "CN"],
  ["harbin", "CN"],
  ["hefei", "CN"],
  ["herat", "AF"],
  ["hiroshima", "JP"],
  ["ho chi minh", "VN"],
  ["hubli", "IN"],
  ["indore", "IN"],
  ["isfahan", "IR"],
  ["jinan", "CN"],
  ["johor bahru", "MY"],
  ["kabul", "AF"],
  ["kaesong", "KP"],
  ["kandahar", "AF"],
  ["kandy", "LK"],
  ["kobe", "JP"],
  ["kozhikode", "IN"],
  ["kuching", "MY"],
  ["kumamoto", "JP"],
  ["lanzhou", "CN"],
  ["lhasa", "CN"],
  ["luoyang", "CN"],
  ["madurai", "IN"],
  ["makassar", "ID"],
  ["malacca", "MY"],
  ["mandalay", "MM"],
  ["mangalore", "IN"],
  ["mashhad", "IR"],
  ["meerut", "IN"],
  ["multan", "PK"],
  ["mysore", "IN"],
  ["mysuru", "IN"],
  ["nagpur", "IN"],
  ["nanning", "CN"],
  ["nashik", "IN"],
  ["ningbo", "CN"],
  ["noida", "IN"],
  ["palembang", "ID"],
  ["patna", "IN"],
  ["penang", "MY"],
  ["phitsanulok", "TH"],
  ["phuket", "TH"],
  ["qingdao", "CN"],
  ["quetta", "PK"],
  ["rajshahi", "BD"],
  ["semarang", "ID"],
  ["sendai", "JP"],
  ["shiraz", "IR"],
  ["sialkot", "PK"],
  ["siem reap", "KH"],
  ["suzhou", "CN"],
  ["sylhet", "BD"],
  ["tabriz", "IR"],
  ["taichung", "TW"],
  ["tainan", "TW"],
  ["thiruvananthapuram", "IN"],
  ["trivandrum", "IN"],
  ["ulsan", "KR"],
  ["varanasi", "IN"],
  ["visakhapatnam", "IN"],
  ["wuxi", "CN"],
  ["xiamen", "CN"],
  ["xuzhou", "CN"],
  ["yekaterinburg", "RU"],
  ["zhongshan", "CN"],
  ["zhuhai", "CN"],

  // More European cities
  ["aarhus", "DK"],
  ["aalborg", "DK"],
  ["antwerp", "BE"],
  ["athens", "GR"],
  ["bari", "IT"],
  ["basel", "CH"],
  ["bergen", "NO"],
  ["birmingham", "GB"],
  ["bologna", "IT"],
  ["bordeaux", "FR"],
  ["bratislava", "SK"],
  ["brno", "CZ"],
  ["bruges", "BE"],
  ["charleroi", "BE"],
  ["clermont-ferrand", "FR"],
  ["cork", "IE"],
  ["debrecen", "HU"],
  ["dortmund", "DE"],
  ["dubrovnik", "HR"],
  ["eindhoven", "NL"],
  ["espoo", "FI"],
  ["essen", "DE"],
  ["galway", "IE"],
  ["gdynia", "PL"],
  ["genova", "IT"],
  ["ghent", "BE"],
  ["gothenburg", "SE"],
  ["graz", "AT"],
  ["hannover", "DE"],
  ["innsbruck", "AT"],
  ["katowice", "PL"],
  ["kazan", "RU"],
  ["kharkiv", "UA"],
  ["kiel", "DE"],
  ["kosice", "SK"],
  ["lausanne", "CH"],
  ["leeds", "GB"],
  ["leipzig", "DE"],
  ["liege", "BE"],
  ["lille", "FR"],
  ["linz", "AT"],
  ["liverpool", "GB"],
  ["lodz", "PL"],
  ["lublin", "PL"],
  ["lugano", "CH"],
  ["lviv", "UA"],
  ["malaga", "ES"],
  ["malmo", "SE"],
  ["mannheim", "DE"],
  ["murcia", "ES"],
  ["nantes", "FR"],
  ["nizhny novgorod", "RU"],
  ["nottingham", "GB"],
  ["novi sad", "RS"],
  ["odessa", "UA"],
  ["odesa", "UA"],
  ["palermo", "IT"],
  ["plovdiv", "BG"],
  ["porto", "PT"],
  ["poznan", "PL"],
  ["rotterdam", "NL"],
  ["saint petersburg", "RU"],
  ["salzburg", "AT"],
  ["samara", "RU"],
  ["sheffield", "GB"],
  ["split", "HR"],
  ["tampere", "FI"],
  ["tartu", "EE"],
  ["thessaloniki", "GR"],
  ["turku", "FI"],
  ["utrecht", "NL"],
  ["valencia", "ES"],
  ["varna", "BG"],
  ["vilnius", "LT"],
  ["wroclaw", "PL"],
  ["zaragoza", "ES"],

  // More North American cities
  ["albuquerque", "US"],
  ["atlanta", "US"],
  ["calgary", "CA"],
  ["cancun", "MX"],
  ["cincinnati", "US"],
  ["cleveland", "US"],
  ["columbus", "US"],
  ["corpus christi", "US"],
  ["durham", "US"],
  ["edmonton", "CA"],
  ["fresno", "US"],
  ["halifax", "CA"],
  ["hamilton", "CA"],
  ["honolulu", "US"],
  ["jacksonville", "US"],
  ["kansas city", "US"],
  ["kitchener", "CA"],
  ["leon", "MX"],
  ["louisville", "US"],
  ["madison", "US"],
  ["merida", "MX"],
  ["mesa", "US"],
  ["milwaukee", "US"],
  ["nashville", "US"],
  ["oakland", "US"],
  ["oklahoma city", "US"],
  ["omaha", "US"],
  ["orlando", "US"],
  ["playa del carmen", "MX"],
  ["portland", "US"],
  ["quebec city", "CA"],
  ["raleigh", "US"],
  ["richmond", "US"],
  ["sacramento", "US"],
  ["san antonio", "US"],
  ["saskatoon", "CA"],
  ["tampa", "US"],
  ["tijuana", "MX"],
  ["toluca", "MX"],
  ["tucson", "US"],
  ["tulsa", "US"],
  ["virginia beach", "US"],
  ["winnipeg", "CA"],

  // More South American cities
  ["arequipa", "PE"],
  ["asuncion", "PY"],
  ["barquisimeto", "VE"],
  ["belem", "BR"],
  ["bucaramanga", "CO"],
  ["campinas", "BR"],
  ["cochabamba", "BO"],
  ["concepcion", "CL"],
  ["cordoba", "AR"],
  ["cuenca", "EC"],
  ["florianopolis", "BR"],
  ["goiania", "BR"],
  ["guarulhos", "BR"],
  ["la plata", "AR"],
  ["maracay", "VE"],
  ["mar del plata", "AR"],
  ["mendoza", "AR"],
  ["natal", "BR"],
  ["pereira", "CO"],
  ["piura", "PE"],
  ["quito", "EC"],
  ["recife", "BR"],
  ["rosario", "AR"],
  ["santa cruz", "BO"],
  ["santa fe", "AR"],
  ["santos", "BR"],
  ["trujillo", "PE"],
  ["tucuman", "AR"],
  ["valparaiso", "CL"],
  ["vitoria", "BR"],

  // More Middle Eastern cities
  ["aqaba", "JO"],
  ["arbil", "IQ"],
  ["erbil", "IQ"],
  ["basra", "IQ"],
  ["dammam", "SA"],
  ["doha", "QA"],
  ["fallujah", "IQ"],
  ["gaziantep", "TR"],
  ["irbid", "JO"],
  ["kirkuk", "IQ"],
  ["kut", "IQ"],
  ["luxor", "EG"],
  ["madinah", "SA"],
  ["medina", "SA"],
  ["mosul", "IQ"],
  ["najaf", "IQ"],
  ["ramallah", "PS"],
  ["salalah", "OM"],
  ["sanliurfa", "TR"],
  ["sulaymaniyah", "IQ"],
  ["tabuk", "SA"],
  ["zarqa", "JO"],

  // More Oceanian cities
  ["cairns", "AU"],
  ["darwin", "AU"],
  ["dunedin", "NZ"],
  ["geelong", "AU"],
  ["gold coast", "AU"],
  ["hamilton", "NZ"],
  ["lae", "PG"],
  ["suva", "FJ"],
  ["tauranga", "NZ"],
  ["townsville", "AU"],
  ["wollongong", "AU"],

  // Alternate spellings / transliterations
  ["antananarivo", "MG"],
  ["beograd", "RS"],
  ["bruxelles", "BE"],
  ["bucuresti", "RO"],
  ["citta del vaticano", "VA"],
  ["ciudad de mexico", "MX"],
  ["constantinople", "TR"],
  ["den haag", "NL"],
  ["firenze", "IT"],
  ["geneve", "CH"],
  ["goteborg", "SE"],
  ["havanna", "CU"],
  ["kobenhavn", "DK"],
  ["koeln", "DE"],
  ["konstantinopel", "TR"],
  ["krung thep", "TH"],
  ["lisboa", "PT"],
  ["lissabon", "PT"],
  ["londra", "GB"],
  ["moskva", "RU"],
  ["munchen", "DE"],
  ["napoli", "IT"],
  ["nueva york", "US"],
  ["pari", "FR"],
  ["pekin", "CN"],
  ["philly", "US"],
  ["praha", "CZ"],
  ["roma", "IT"],
  ["sao paulo", "BR"],
  ["singapur", "SG"],
  ["teheran", "IR"],
  ["tel-aviv", "IL"],
  ["tokio", "JP"],
  ["torino", "IT"],
  ["varsavia", "PL"],
  ["warszawa", "PL"],
  ["wien", "AT"],

  // Common informal / short names
  ["hk", "HK"],
  ["la", "US"],
  ["sg", "SG"],
  ["vegas", "US"],
]);
