// Complete ISO 3166-1 alpha-2 country data
// Sorted alphabetically by country code

export const COUNTRIES = [
  { code: "AD", name: "Andorra", aliases: [], flag: "\u{1F1E6}\u{1F1E9}", languages: [] },
  { code: "AE", name: "United Arab Emirates", aliases: ["uae", "emirates"], flag: "\u{1F1E6}\u{1F1EA}", languages: [] },
  { code: "AF", name: "Afghanistan", aliases: [], flag: "\u{1F1E6}\u{1F1EB}", languages: [] },
  { code: "AG", name: "Antigua and Barbuda", aliases: [], flag: "\u{1F1E6}\u{1F1EC}", languages: [] },
  { code: "AI", name: "Anguilla", aliases: [], flag: "\u{1F1E6}\u{1F1EE}", languages: [] },
  { code: "AL", name: "Albania", aliases: [], flag: "\u{1F1E6}\u{1F1F1}", languages: [] },
  { code: "AM", name: "Armenia", aliases: [], flag: "\u{1F1E6}\u{1F1F2}", languages: ["hy"] },
  { code: "AO", name: "Angola", aliases: [], flag: "\u{1F1E6}\u{1F1F4}", languages: [] },
  { code: "AQ", name: "Antarctica", aliases: [], flag: "\u{1F1E6}\u{1F1F6}", languages: [] },
  { code: "AR", name: "Argentina", aliases: [], flag: "\u{1F1E6}\u{1F1F7}", languages: [] },
  { code: "AS", name: "American Samoa", aliases: [], flag: "\u{1F1E6}\u{1F1F8}", languages: [] },
  { code: "AT", name: "Austria", aliases: [], flag: "\u{1F1E6}\u{1F1F9}", languages: [] },
  { code: "AU", name: "Australia", aliases: ["aus", "aussie"], flag: "\u{1F1E6}\u{1F1FA}", languages: [] },
  { code: "AW", name: "Aruba", aliases: [], flag: "\u{1F1E6}\u{1F1FC}", languages: [] },
  { code: "AX", name: "Aland Islands", aliases: [], flag: "\u{1F1E6}\u{1F1FD}", languages: [] },
  { code: "AZ", name: "Azerbaijan", aliases: [], flag: "\u{1F1E6}\u{1F1FF}", languages: ["az"] },
  { code: "BA", name: "Bosnia and Herzegovina", aliases: ["bosnia"], flag: "\u{1F1E7}\u{1F1E6}", languages: [] },
  { code: "BB", name: "Barbados", aliases: [], flag: "\u{1F1E7}\u{1F1E7}", languages: [] },
  { code: "BD", name: "Bangladesh", aliases: [], flag: "\u{1F1E7}\u{1F1E9}", languages: [] },
  { code: "BE", name: "Belgium", aliases: [], flag: "\u{1F1E7}\u{1F1EA}", languages: [] },
  { code: "BF", name: "Burkina Faso", aliases: [], flag: "\u{1F1E7}\u{1F1EB}", languages: [] },
  { code: "BG", name: "Bulgaria", aliases: [], flag: "\u{1F1E7}\u{1F1EC}", languages: [] },
  { code: "BH", name: "Bahrain", aliases: [], flag: "\u{1F1E7}\u{1F1ED}", languages: [] },
  { code: "BI", name: "Burundi", aliases: [], flag: "\u{1F1E7}\u{1F1EE}", languages: [] },
  { code: "BJ", name: "Benin", aliases: [], flag: "\u{1F1E7}\u{1F1EF}", languages: [] },
  { code: "BL", name: "Saint Barthelemy", aliases: [], flag: "\u{1F1E7}\u{1F1F1}", languages: [] },
  { code: "BM", name: "Bermuda", aliases: [], flag: "\u{1F1E7}\u{1F1F2}", languages: [] },
  { code: "BN", name: "Brunei Darussalam", aliases: ["brunei"], flag: "\u{1F1E7}\u{1F1F3}", languages: [] },
  { code: "BO", name: "Bolivia", aliases: [], flag: "\u{1F1E7}\u{1F1F4}", languages: [] },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", aliases: ["caribbean netherlands"], flag: "\u{1F1E7}\u{1F1F6}", languages: [] },
  { code: "BR", name: "Brazil", aliases: ["brasil"], flag: "\u{1F1E7}\u{1F1F7}", languages: [] },
  { code: "BS", name: "Bahamas", aliases: ["the bahamas"], flag: "\u{1F1E7}\u{1F1F8}", languages: [] },
  { code: "BT", name: "Bhutan", aliases: [], flag: "\u{1F1E7}\u{1F1F9}", languages: [] },
  { code: "BV", name: "Bouvet Island", aliases: [], flag: "\u{1F1E7}\u{1F1FB}", languages: [] },
  { code: "BW", name: "Botswana", aliases: [], flag: "\u{1F1E7}\u{1F1FC}", languages: [] },
  { code: "BY", name: "Belarus", aliases: [], flag: "\u{1F1E7}\u{1F1FE}", languages: [] },
  { code: "BZ", name: "Belize", aliases: [], flag: "\u{1F1E7}\u{1F1FF}", languages: [] },
  { code: "CA", name: "Canada", aliases: [], flag: "\u{1F1E8}\u{1F1E6}", languages: [] },
  { code: "CC", name: "Cocos (Keeling) Islands", aliases: [], flag: "\u{1F1E8}\u{1F1E8}", languages: [] },
  { code: "CD", name: "Congo, Democratic Republic of the", aliases: ["drc", "democratic republic of congo", "dr congo"], flag: "\u{1F1E8}\u{1F1E9}", languages: [] },
  { code: "CF", name: "Central African Republic", aliases: ["car"], flag: "\u{1F1E8}\u{1F1EB}", languages: [] },
  { code: "CG", name: "Congo", aliases: ["republic of congo", "congo-brazzaville"], flag: "\u{1F1E8}\u{1F1EC}", languages: [] },
  { code: "CH", name: "Switzerland", aliases: ["swiss"], flag: "\u{1F1E8}\u{1F1ED}", languages: [] },
  { code: "CI", name: "Cote d'Ivoire", aliases: ["ivory coast"], flag: "\u{1F1E8}\u{1F1EE}", languages: [] },
  { code: "CK", name: "Cook Islands", aliases: [], flag: "\u{1F1E8}\u{1F1F0}", languages: [] },
  { code: "CL", name: "Chile", aliases: [], flag: "\u{1F1E8}\u{1F1F1}", languages: [] },
  { code: "CM", name: "Cameroon", aliases: [], flag: "\u{1F1E8}\u{1F1F2}", languages: [] },
  { code: "CN", name: "China", aliases: ["prc", "peoples republic of china", "people's republic of china"], flag: "\u{1F1E8}\u{1F1F3}", languages: [] },
  { code: "CO", name: "Colombia", aliases: [], flag: "\u{1F1E8}\u{1F1F4}", languages: [] },
  { code: "CR", name: "Costa Rica", aliases: [], flag: "\u{1F1E8}\u{1F1F7}", languages: [] },
  { code: "CU", name: "Cuba", aliases: [], flag: "\u{1F1E8}\u{1F1FA}", languages: [] },
  { code: "CV", name: "Cabo Verde", aliases: ["cape verde"], flag: "\u{1F1E8}\u{1F1FB}", languages: [] },
  { code: "CW", name: "Curacao", aliases: [], flag: "\u{1F1E8}\u{1F1FC}", languages: [] },
  { code: "CX", name: "Christmas Island", aliases: [], flag: "\u{1F1E8}\u{1F1FD}", languages: [] },
  { code: "CY", name: "Cyprus", aliases: [], flag: "\u{1F1E8}\u{1F1FE}", languages: [] },
  { code: "CZ", name: "Czechia", aliases: ["czech republic"], flag: "\u{1F1E8}\u{1F1FF}", languages: [] },
  { code: "DE", name: "Germany", aliases: ["deutschland"], flag: "\u{1F1E9}\u{1F1EA}", languages: [] },
  { code: "DJ", name: "Djibouti", aliases: [], flag: "\u{1F1E9}\u{1F1EF}", languages: [] },
  { code: "DK", name: "Denmark", aliases: [], flag: "\u{1F1E9}\u{1F1F0}", languages: [] },
  { code: "DM", name: "Dominica", aliases: [], flag: "\u{1F1E9}\u{1F1F2}", languages: [] },
  { code: "DO", name: "Dominican Republic", aliases: [], flag: "\u{1F1E9}\u{1F1F4}", languages: [] },
  { code: "DZ", name: "Algeria", aliases: [], flag: "\u{1F1E9}\u{1F1FF}", languages: [] },
  { code: "EC", name: "Ecuador", aliases: [], flag: "\u{1F1EA}\u{1F1E8}", languages: [] },
  { code: "EE", name: "Estonia", aliases: [], flag: "\u{1F1EA}\u{1F1EA}", languages: [] },
  { code: "EG", name: "Egypt", aliases: [], flag: "\u{1F1EA}\u{1F1EC}", languages: [] },
  { code: "EH", name: "Western Sahara", aliases: [], flag: "\u{1F1EA}\u{1F1ED}", languages: [] },
  { code: "ER", name: "Eritrea", aliases: [], flag: "\u{1F1EA}\u{1F1F7}", languages: ["ti"] },
  { code: "ES", name: "Spain", aliases: ["espana"], flag: "\u{1F1EA}\u{1F1F8}", languages: [] },
  { code: "ET", name: "Ethiopia", aliases: [], flag: "\u{1F1EA}\u{1F1F9}", languages: ["am"] },
  { code: "FI", name: "Finland", aliases: [], flag: "\u{1F1EB}\u{1F1EE}", languages: [] },
  { code: "FJ", name: "Fiji", aliases: [], flag: "\u{1F1EB}\u{1F1EF}", languages: [] },
  { code: "FK", name: "Falkland Islands (Malvinas)", aliases: ["falkland islands", "falklands"], flag: "\u{1F1EB}\u{1F1F0}", languages: [] },
  { code: "FM", name: "Micronesia (Federated States of)", aliases: ["micronesia"], flag: "\u{1F1EB}\u{1F1F2}", languages: [] },
  { code: "FO", name: "Faroe Islands", aliases: [], flag: "\u{1F1EB}\u{1F1F4}", languages: [] },
  { code: "FR", name: "France", aliases: [], flag: "\u{1F1EB}\u{1F1F7}", languages: [] },
  { code: "GA", name: "Gabon", aliases: [], flag: "\u{1F1EC}\u{1F1E6}", languages: [] },
  { code: "GB", name: "United Kingdom", aliases: ["uk", "england", "britain", "great britain", "u.k.", "u.k"], flag: "\u{1F1EC}\u{1F1E7}", languages: [] },
  { code: "GD", name: "Grenada", aliases: [], flag: "\u{1F1EC}\u{1F1E9}", languages: [] },
  { code: "GE", name: "Georgia", aliases: [], flag: "\u{1F1EC}\u{1F1EA}", languages: ["ka"] },
  { code: "GF", name: "French Guiana", aliases: [], flag: "\u{1F1EC}\u{1F1EB}", languages: [] },
  { code: "GG", name: "Guernsey", aliases: [], flag: "\u{1F1EC}\u{1F1EC}", languages: [] },
  { code: "GH", name: "Ghana", aliases: [], flag: "\u{1F1EC}\u{1F1ED}", languages: [] },
  { code: "GI", name: "Gibraltar", aliases: [], flag: "\u{1F1EC}\u{1F1EE}", languages: [] },
  { code: "GL", name: "Greenland", aliases: [], flag: "\u{1F1EC}\u{1F1F1}", languages: [] },
  { code: "GM", name: "Gambia", aliases: ["the gambia"], flag: "\u{1F1EC}\u{1F1F2}", languages: [] },
  { code: "GN", name: "Guinea", aliases: [], flag: "\u{1F1EC}\u{1F1F3}", languages: [] },
  { code: "GP", name: "Guadeloupe", aliases: [], flag: "\u{1F1EC}\u{1F1F5}", languages: [] },
  { code: "GQ", name: "Equatorial Guinea", aliases: [], flag: "\u{1F1EC}\u{1F1F6}", languages: [] },
  { code: "GR", name: "Greece", aliases: ["hellas"], flag: "\u{1F1EC}\u{1F1F7}", languages: ["el"] },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", aliases: [], flag: "\u{1F1EC}\u{1F1F8}", languages: [] },
  { code: "GT", name: "Guatemala", aliases: [], flag: "\u{1F1EC}\u{1F1F9}", languages: [] },
  { code: "GU", name: "Guam", aliases: [], flag: "\u{1F1EC}\u{1F1FA}", languages: [] },
  { code: "GW", name: "Guinea-Bissau", aliases: [], flag: "\u{1F1EC}\u{1F1FC}", languages: [] },
  { code: "GY", name: "Guyana", aliases: [], flag: "\u{1F1EC}\u{1F1FE}", languages: [] },
  { code: "HK", name: "Hong Kong", aliases: [], flag: "\u{1F1ED}\u{1F1F0}", languages: [] },
  { code: "HM", name: "Heard Island and McDonald Islands", aliases: [], flag: "\u{1F1ED}\u{1F1F2}", languages: [] },
  { code: "HN", name: "Honduras", aliases: [], flag: "\u{1F1ED}\u{1F1F3}", languages: [] },
  { code: "HR", name: "Croatia", aliases: ["hrvatska"], flag: "\u{1F1ED}\u{1F1F7}", languages: [] },
  { code: "HT", name: "Haiti", aliases: [], flag: "\u{1F1ED}\u{1F1F9}", languages: [] },
  { code: "HU", name: "Hungary", aliases: [], flag: "\u{1F1ED}\u{1F1FA}", languages: [] },
  { code: "ID", name: "Indonesia", aliases: [], flag: "\u{1F1EE}\u{1F1E9}", languages: [] },
  { code: "IE", name: "Ireland", aliases: ["eire"], flag: "\u{1F1EE}\u{1F1EA}", languages: [] },
  { code: "IL", name: "Israel", aliases: [], flag: "\u{1F1EE}\u{1F1F1}", languages: ["he"] },
  { code: "IM", name: "Isle of Man", aliases: [], flag: "\u{1F1EE}\u{1F1F2}", languages: [] },
  { code: "IN", name: "India", aliases: ["bharat"], flag: "\u{1F1EE}\u{1F1F3}", languages: [] },
  { code: "IO", name: "British Indian Ocean Territory", aliases: [], flag: "\u{1F1EE}\u{1F1F4}", languages: [] },
  { code: "IQ", name: "Iraq", aliases: [], flag: "\u{1F1EE}\u{1F1F6}", languages: [] },
  { code: "IR", name: "Iran", aliases: ["islamic republic of iran", "persia"], flag: "\u{1F1EE}\u{1F1F7}", languages: [] },
  { code: "IS", name: "Iceland", aliases: [], flag: "\u{1F1EE}\u{1F1F8}", languages: [] },
  { code: "IT", name: "Italy", aliases: ["italia"], flag: "\u{1F1EE}\u{1F1F9}", languages: [] },
  { code: "JE", name: "Jersey", aliases: [], flag: "\u{1F1EF}\u{1F1EA}", languages: [] },
  { code: "JM", name: "Jamaica", aliases: [], flag: "\u{1F1EF}\u{1F1F2}", languages: [] },
  { code: "JO", name: "Jordan", aliases: [], flag: "\u{1F1EF}\u{1F1F4}", languages: [] },
  { code: "JP", name: "Japan", aliases: ["nippon", "nihon"], flag: "\u{1F1EF}\u{1F1F5}", languages: ["ja"] },
  { code: "KE", name: "Kenya", aliases: [], flag: "\u{1F1F0}\u{1F1EA}", languages: [] },
  { code: "KG", name: "Kyrgyzstan", aliases: [], flag: "\u{1F1F0}\u{1F1EC}", languages: [] },
  { code: "KH", name: "Cambodia", aliases: ["kampuchea"], flag: "\u{1F1F0}\u{1F1ED}", languages: ["km"] },
  { code: "KI", name: "Kiribati", aliases: [], flag: "\u{1F1F0}\u{1F1EE}", languages: [] },
  { code: "KM", name: "Comoros", aliases: [], flag: "\u{1F1F0}\u{1F1F2}", languages: [] },
  { code: "KN", name: "Saint Kitts and Nevis", aliases: [], flag: "\u{1F1F0}\u{1F1F3}", languages: [] },
  { code: "KP", name: "North Korea", aliases: ["dprk", "democratic people's republic of korea"], flag: "\u{1F1F0}\u{1F1F5}", languages: [] },
  { code: "KR", name: "South Korea", aliases: ["korea", "republic of korea"], flag: "\u{1F1F0}\u{1F1F7}", languages: ["ko"] },
  { code: "KW", name: "Kuwait", aliases: [], flag: "\u{1F1F0}\u{1F1FC}", languages: [] },
  { code: "KY", name: "Cayman Islands", aliases: [], flag: "\u{1F1F0}\u{1F1FE}", languages: [] },
  { code: "KZ", name: "Kazakhstan", aliases: [], flag: "\u{1F1F0}\u{1F1FF}", languages: [] },
  { code: "LA", name: "Laos", aliases: ["lao people's democratic republic"], flag: "\u{1F1F1}\u{1F1E6}", languages: ["lo"] },
  { code: "LB", name: "Lebanon", aliases: [], flag: "\u{1F1F1}\u{1F1E7}", languages: [] },
  { code: "LC", name: "Saint Lucia", aliases: [], flag: "\u{1F1F1}\u{1F1E8}", languages: [] },
  { code: "LI", name: "Liechtenstein", aliases: [], flag: "\u{1F1F1}\u{1F1EE}", languages: [] },
  { code: "LK", name: "Sri Lanka", aliases: [], flag: "\u{1F1F1}\u{1F1F0}", languages: ["si"] },
  { code: "LR", name: "Liberia", aliases: [], flag: "\u{1F1F1}\u{1F1F7}", languages: [] },
  { code: "LS", name: "Lesotho", aliases: [], flag: "\u{1F1F1}\u{1F1F8}", languages: [] },
  { code: "LT", name: "Lithuania", aliases: [], flag: "\u{1F1F1}\u{1F1F9}", languages: [] },
  { code: "LU", name: "Luxembourg", aliases: [], flag: "\u{1F1F1}\u{1F1FA}", languages: [] },
  { code: "LV", name: "Latvia", aliases: [], flag: "\u{1F1F1}\u{1F1FB}", languages: [] },
  { code: "LY", name: "Libya", aliases: [], flag: "\u{1F1F1}\u{1F1FE}", languages: [] },
  { code: "MA", name: "Morocco", aliases: [], flag: "\u{1F1F2}\u{1F1E6}", languages: [] },
  { code: "MC", name: "Monaco", aliases: [], flag: "\u{1F1F2}\u{1F1E8}", languages: [] },
  { code: "MD", name: "Moldova", aliases: ["republic of moldova"], flag: "\u{1F1F2}\u{1F1E9}", languages: [] },
  { code: "ME", name: "Montenegro", aliases: [], flag: "\u{1F1F2}\u{1F1EA}", languages: [] },
  { code: "MF", name: "Saint Martin (French part)", aliases: ["saint martin"], flag: "\u{1F1F2}\u{1F1EB}", languages: [] },
  { code: "MG", name: "Madagascar", aliases: [], flag: "\u{1F1F2}\u{1F1EC}", languages: [] },
  { code: "MH", name: "Marshall Islands", aliases: [], flag: "\u{1F1F2}\u{1F1ED}", languages: [] },
  { code: "MK", name: "North Macedonia", aliases: ["macedonia"], flag: "\u{1F1F2}\u{1F1F0}", languages: [] },
  { code: "ML", name: "Mali", aliases: [], flag: "\u{1F1F2}\u{1F1F1}", languages: [] },
  { code: "MM", name: "Myanmar", aliases: ["burma"], flag: "\u{1F1F2}\u{1F1F2}", languages: ["my"] },
  { code: "MN", name: "Mongolia", aliases: [], flag: "\u{1F1F2}\u{1F1F3}", languages: ["mn"] },
  { code: "MO", name: "Macao", aliases: ["macau"], flag: "\u{1F1F2}\u{1F1F4}", languages: [] },
  { code: "MP", name: "Northern Mariana Islands", aliases: [], flag: "\u{1F1F2}\u{1F1F5}", languages: [] },
  { code: "MQ", name: "Martinique", aliases: [], flag: "\u{1F1F2}\u{1F1F6}", languages: [] },
  { code: "MR", name: "Mauritania", aliases: [], flag: "\u{1F1F2}\u{1F1F7}", languages: [] },
  { code: "MS", name: "Montserrat", aliases: [], flag: "\u{1F1F2}\u{1F1F8}", languages: [] },
  { code: "MT", name: "Malta", aliases: [], flag: "\u{1F1F2}\u{1F1F9}", languages: [] },
  { code: "MU", name: "Mauritius", aliases: [], flag: "\u{1F1F2}\u{1F1FA}", languages: [] },
  { code: "MV", name: "Maldives", aliases: [], flag: "\u{1F1F2}\u{1F1FB}", languages: [] },
  { code: "MW", name: "Malawi", aliases: [], flag: "\u{1F1F2}\u{1F1FC}", languages: [] },
  { code: "MX", name: "Mexico", aliases: [], flag: "\u{1F1F2}\u{1F1FD}", languages: [] },
  { code: "MY", name: "Malaysia", aliases: [], flag: "\u{1F1F2}\u{1F1FE}", languages: [] },
  { code: "MZ", name: "Mozambique", aliases: [], flag: "\u{1F1F2}\u{1F1FF}", languages: [] },
  { code: "NA", name: "Namibia", aliases: [], flag: "\u{1F1F3}\u{1F1E6}", languages: [] },
  { code: "NC", name: "New Caledonia", aliases: [], flag: "\u{1F1F3}\u{1F1E8}", languages: [] },
  { code: "NE", name: "Niger", aliases: [], flag: "\u{1F1F3}\u{1F1EA}", languages: [] },
  { code: "NF", name: "Norfolk Island", aliases: [], flag: "\u{1F1F3}\u{1F1EB}", languages: [] },
  { code: "NG", name: "Nigeria", aliases: [], flag: "\u{1F1F3}\u{1F1EC}", languages: [] },
  { code: "NI", name: "Nicaragua", aliases: [], flag: "\u{1F1F3}\u{1F1EE}", languages: [] },
  { code: "NL", name: "Netherlands", aliases: ["holland", "the netherlands"], flag: "\u{1F1F3}\u{1F1F1}", languages: [] },
  { code: "NO", name: "Norway", aliases: [], flag: "\u{1F1F3}\u{1F1F4}", languages: [] },
  { code: "NP", name: "Nepal", aliases: [], flag: "\u{1F1F3}\u{1F1F5}", languages: ["ne"] },
  { code: "NR", name: "Nauru", aliases: [], flag: "\u{1F1F3}\u{1F1F7}", languages: [] },
  { code: "NU", name: "Niue", aliases: [], flag: "\u{1F1F3}\u{1F1FA}", languages: [] },
  { code: "NZ", name: "New Zealand", aliases: ["aotearoa"], flag: "\u{1F1F3}\u{1F1FF}", languages: [] },
  { code: "OM", name: "Oman", aliases: [], flag: "\u{1F1F4}\u{1F1F2}", languages: [] },
  { code: "PA", name: "Panama", aliases: [], flag: "\u{1F1F5}\u{1F1E6}", languages: [] },
  { code: "PE", name: "Peru", aliases: [], flag: "\u{1F1F5}\u{1F1EA}", languages: [] },
  { code: "PF", name: "French Polynesia", aliases: ["tahiti"], flag: "\u{1F1F5}\u{1F1EB}", languages: [] },
  { code: "PG", name: "Papua New Guinea", aliases: ["png"], flag: "\u{1F1F5}\u{1F1EC}", languages: [] },
  { code: "PH", name: "Philippines", aliases: ["pilipinas"], flag: "\u{1F1F5}\u{1F1ED}", languages: [] },
  { code: "PK", name: "Pakistan", aliases: [], flag: "\u{1F1F5}\u{1F1F0}", languages: [] },
  { code: "PL", name: "Poland", aliases: ["polska"], flag: "\u{1F1F5}\u{1F1F1}", languages: [] },
  { code: "PM", name: "Saint Pierre and Miquelon", aliases: [], flag: "\u{1F1F5}\u{1F1F2}", languages: [] },
  { code: "PN", name: "Pitcairn", aliases: ["pitcairn islands"], flag: "\u{1F1F5}\u{1F1F3}", languages: [] },
  { code: "PR", name: "Puerto Rico", aliases: [], flag: "\u{1F1F5}\u{1F1F7}", languages: [] },
  { code: "PS", name: "Palestine, State of", aliases: ["palestine"], flag: "\u{1F1F5}\u{1F1F8}", languages: [] },
  { code: "PT", name: "Portugal", aliases: [], flag: "\u{1F1F5}\u{1F1F9}", languages: [] },
  { code: "PW", name: "Palau", aliases: [], flag: "\u{1F1F5}\u{1F1FC}", languages: [] },
  { code: "PY", name: "Paraguay", aliases: [], flag: "\u{1F1F5}\u{1F1FE}", languages: [] },
  { code: "QA", name: "Qatar", aliases: [], flag: "\u{1F1F6}\u{1F1E6}", languages: [] },
  { code: "RE", name: "Reunion", aliases: [], flag: "\u{1F1F7}\u{1F1EA}", languages: [] },
  { code: "RO", name: "Romania", aliases: [], flag: "\u{1F1F7}\u{1F1F4}", languages: [] },
  { code: "RS", name: "Serbia", aliases: [], flag: "\u{1F1F7}\u{1F1F8}", languages: [] },
  { code: "RU", name: "Russia", aliases: ["russian federation"], flag: "\u{1F1F7}\u{1F1FA}", languages: [] },
  { code: "RW", name: "Rwanda", aliases: [], flag: "\u{1F1F7}\u{1F1FC}", languages: [] },
  { code: "SA", name: "Saudi Arabia", aliases: ["ksa", "kingdom of saudi arabia"], flag: "\u{1F1F8}\u{1F1E6}", languages: [] },
  { code: "SB", name: "Solomon Islands", aliases: [], flag: "\u{1F1F8}\u{1F1E7}", languages: [] },
  { code: "SC", name: "Seychelles", aliases: [], flag: "\u{1F1F8}\u{1F1E8}", languages: [] },
  { code: "SD", name: "Sudan", aliases: [], flag: "\u{1F1F8}\u{1F1E9}", languages: [] },
  { code: "SE", name: "Sweden", aliases: ["sverige"], flag: "\u{1F1F8}\u{1F1EA}", languages: [] },
  { code: "SG", name: "Singapore", aliases: [], flag: "\u{1F1F8}\u{1F1EC}", languages: [] },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", aliases: ["saint helena"], flag: "\u{1F1F8}\u{1F1ED}", languages: [] },
  { code: "SI", name: "Slovenia", aliases: [], flag: "\u{1F1F8}\u{1F1EE}", languages: [] },
  { code: "SJ", name: "Svalbard and Jan Mayen", aliases: [], flag: "\u{1F1F8}\u{1F1EF}", languages: [] },
  { code: "SK", name: "Slovakia", aliases: [], flag: "\u{1F1F8}\u{1F1F0}", languages: [] },
  { code: "SL", name: "Sierra Leone", aliases: [], flag: "\u{1F1F8}\u{1F1F1}", languages: [] },
  { code: "SM", name: "San Marino", aliases: [], flag: "\u{1F1F8}\u{1F1F2}", languages: [] },
  { code: "SN", name: "Senegal", aliases: [], flag: "\u{1F1F8}\u{1F1F3}", languages: [] },
  { code: "SO", name: "Somalia", aliases: [], flag: "\u{1F1F8}\u{1F1F4}", languages: [] },
  { code: "SR", name: "Suriname", aliases: [], flag: "\u{1F1F8}\u{1F1F7}", languages: [] },
  { code: "SS", name: "South Sudan", aliases: [], flag: "\u{1F1F8}\u{1F1F8}", languages: [] },
  { code: "ST", name: "Sao Tome and Principe", aliases: [], flag: "\u{1F1F8}\u{1F1F9}", languages: [] },
  { code: "SV", name: "El Salvador", aliases: [], flag: "\u{1F1F8}\u{1F1FB}", languages: [] },
  { code: "SX", name: "Sint Maarten (Dutch part)", aliases: ["sint maarten"], flag: "\u{1F1F8}\u{1F1FD}", languages: [] },
  { code: "SY", name: "Syria", aliases: ["syrian arab republic"], flag: "\u{1F1F8}\u{1F1FE}", languages: [] },
  { code: "SZ", name: "Eswatini", aliases: ["swaziland"], flag: "\u{1F1F8}\u{1F1FF}", languages: [] },
  { code: "TC", name: "Turks and Caicos Islands", aliases: [], flag: "\u{1F1F9}\u{1F1E8}", languages: [] },
  { code: "TD", name: "Chad", aliases: [], flag: "\u{1F1F9}\u{1F1E9}", languages: [] },
  { code: "TF", name: "French Southern Territories", aliases: [], flag: "\u{1F1F9}\u{1F1EB}", languages: [] },
  { code: "TG", name: "Togo", aliases: [], flag: "\u{1F1F9}\u{1F1EC}", languages: [] },
  { code: "TH", name: "Thailand", aliases: [], flag: "\u{1F1F9}\u{1F1ED}", languages: ["th"] },
  { code: "TJ", name: "Tajikistan", aliases: [], flag: "\u{1F1F9}\u{1F1EF}", languages: [] },
  { code: "TK", name: "Tokelau", aliases: [], flag: "\u{1F1F9}\u{1F1F0}", languages: [] },
  { code: "TL", name: "Timor-Leste", aliases: ["east timor"], flag: "\u{1F1F9}\u{1F1F1}", languages: [] },
  { code: "TM", name: "Turkmenistan", aliases: [], flag: "\u{1F1F9}\u{1F1F2}", languages: [] },
  { code: "TN", name: "Tunisia", aliases: [], flag: "\u{1F1F9}\u{1F1F3}", languages: [] },
  { code: "TO", name: "Tonga", aliases: [], flag: "\u{1F1F9}\u{1F1F4}", languages: [] },
  { code: "TR", name: "Turkey", aliases: ["turkiye"], flag: "\u{1F1F9}\u{1F1F7}", languages: [] },
  { code: "TT", name: "Trinidad and Tobago", aliases: [], flag: "\u{1F1F9}\u{1F1F9}", languages: [] },
  { code: "TV", name: "Tuvalu", aliases: [], flag: "\u{1F1F9}\u{1F1FB}", languages: [] },
  { code: "TW", name: "Taiwan", aliases: ["republic of china", "roc"], flag: "\u{1F1F9}\u{1F1FC}", languages: [] },
  { code: "TZ", name: "Tanzania", aliases: ["united republic of tanzania"], flag: "\u{1F1F9}\u{1F1FF}", languages: [] },
  { code: "UA", name: "Ukraine", aliases: [], flag: "\u{1F1FA}\u{1F1E6}", languages: ["uk"] },
  { code: "UG", name: "Uganda", aliases: [], flag: "\u{1F1FA}\u{1F1EC}", languages: [] },
  { code: "UM", name: "United States Minor Outlying Islands", aliases: [], flag: "\u{1F1FA}\u{1F1F2}", languages: [] },
  { code: "US", name: "United States", aliases: ["usa", "u.s.a", "u.s.a.", "america", "united states of america", "u.s.", "u.s"], flag: "\u{1F1FA}\u{1F1F8}", languages: [] },
  { code: "UY", name: "Uruguay", aliases: [], flag: "\u{1F1FA}\u{1F1FE}", languages: [] },
  { code: "UZ", name: "Uzbekistan", aliases: [], flag: "\u{1F1FA}\u{1F1FF}", languages: [] },
  { code: "VA", name: "Holy See", aliases: ["vatican", "vatican city"], flag: "\u{1F1FB}\u{1F1E6}", languages: [] },
  { code: "VC", name: "Saint Vincent and the Grenadines", aliases: [], flag: "\u{1F1FB}\u{1F1E8}", languages: [] },
  { code: "VE", name: "Venezuela", aliases: [], flag: "\u{1F1FB}\u{1F1EA}", languages: [] },
  { code: "VG", name: "Virgin Islands (British)", aliases: ["british virgin islands", "bvi"], flag: "\u{1F1FB}\u{1F1EC}", languages: [] },
  { code: "VI", name: "Virgin Islands (U.S.)", aliases: ["us virgin islands", "usvi"], flag: "\u{1F1FB}\u{1F1EE}", languages: [] },
  { code: "VN", name: "Vietnam", aliases: ["viet nam"], flag: "\u{1F1FB}\u{1F1F3}", languages: ["vi"] },
  { code: "VU", name: "Vanuatu", aliases: [], flag: "\u{1F1FB}\u{1F1FA}", languages: [] },
  { code: "WF", name: "Wallis and Futuna", aliases: [], flag: "\u{1F1FC}\u{1F1EB}", languages: [] },
  { code: "WS", name: "Samoa", aliases: [], flag: "\u{1F1FC}\u{1F1F8}", languages: [] },
  { code: "YE", name: "Yemen", aliases: [], flag: "\u{1F1FE}\u{1F1EA}", languages: [] },
  { code: "YT", name: "Mayotte", aliases: [], flag: "\u{1F1FE}\u{1F1F9}", languages: [] },
  { code: "ZA", name: "South Africa", aliases: ["rsa"], flag: "\u{1F1FF}\u{1F1E6}", languages: [] },
  { code: "ZM", name: "Zambia", aliases: [], flag: "\u{1F1FF}\u{1F1F2}", languages: [] },
  { code: "ZW", name: "Zimbabwe", aliases: [], flag: "\u{1F1FF}\u{1F1FC}", languages: [] },
];

// Precomputed lookup: country code -> country object
export const COUNTRY_BY_CODE = Object.fromEntries(COUNTRIES.map(c => [c.code, c]));

// Precomputed lookup: lowercase name or alias -> country code
export const COUNTRY_BY_NAME = new Map();
for (const c of COUNTRIES) {
  COUNTRY_BY_NAME.set(c.name.toLowerCase(), c.code);
  for (const alias of c.aliases) {
    COUNTRY_BY_NAME.set(alias.toLowerCase(), c.code);
  }
}

// Precomputed lookup: language code -> country code (only unambiguous single-country languages)
export const LANGUAGE_TO_COUNTRY = new Map();
for (const c of COUNTRIES) {
  for (const lang of c.languages) {
    LANGUAGE_TO_COUNTRY.set(lang, c.code);
  }
}
